WITH TOTAL_MILES_AND_FARE AS
(
SELECT 
	NVL(rc.RATECODE_DESCRIPTION, td.RATECODEID) AS RATECODEID, 
	td.DAY_OF_WEEK, 
	td.HOUR_OF_DAY, 
	SUM(td.TRIP_DISTANCE) AS TOTAL_DISTANCE_MILES, 
	SUM(td.FARE_AMOUNT) AS FARE_AMOUNT
FROM YT_TRIP_DATA td
LEFT OUTER JOIN YT_DD_RATECODEID rc
ON td.RATECODEID = rc.RATECODE_ID
WHERE trunc(td.TPEP_PICKUP_DATETIME, 'MM') >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -4) 
	AND td.RATECODEID IS NOT NULL 
	AND td.PAYMENT_TYPE <> 3 -- This condition is to filter out the "No charge" trips
GROUP BY NVL(rc.RATECODE_DESCRIPTION, td.RATECODEID), td.DAY_OF_WEEK, td.HOUR_OF_DAY
)
SELECT RATECODEID, DAY_OF_WEEK, HOUR_OF_DAY, FARE_AMOUNT, TOTAL_DISTANCE_MILES, 
CASE WHEN TOTAL_DISTANCE_MILES = 0 OR FARE_AMOUNT = 0 THEN 0 ELSE ROUND(FARE_AMOUNT/TOTAL_DISTANCE_MILES, 2) END AS AVG_FARE_AMT_PER_MILE 
FROM TOTAL_MILES_AND_FARE TMF ORDER BY 1;