ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE ;

CREATE TABLESPACE amithdata DATAFILE 'amithdata.dbf' SIZE 200M AUTOEXTEND ON;

CREATE USER amith IDENTIFIED BY amith DEFAULT TABLESPACE amithdata;

GRANT dba TO amith;

COMMIT;