SELECT 
	TRUNC(td.TPEP_PICKUP_DATETIME, 'IW') AS START_DATE_OF_WEEK, 
	NVL((lzp.BOROUGH||' - '||lzp.ZONEE), td.PULOCATIONID) AS PICKUP_LOCATION,
	NVL((lzd.BOROUGH||' - '||lzd.ZONEE), td.DOLOCATIONID) AS DROPOFF_LOCATION,
	MIN(td.TRIP_DISTANCE) AS SHORTEST_PATH,
	MAX(td.TRIP_DISTANCE) AS LONGEST_PATH
FROM YT_TRIP_DATA td
LEFT OUTER JOIN YT_DD_LOCANDZONES lzp
ON td.PULOCATIONID = lzp.LOCATION_ID 
LEFT OUTER JOIN YT_DD_LOCANDZONES lzd
ON td.DOLOCATIONID = lzd.LOCATION_ID 
WHERE TRUNC(td.TPEP_PICKUP_DATETIME, 'MM') >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -4)
AND td.RATECODEID IS NOT NULL
GROUP BY TRUNC(td.TPEP_PICKUP_DATETIME, 'IW'), NVL((lzp.BOROUGH||' - '||lzp.ZONEE), td.PULOCATIONID), NVL((lzd.BOROUGH||' - '||lzd.ZONEE), td.DOLOCATIONID)
ORDER BY 1,2,3,4