SELECT 
	TRUNC(td.TPEP_PICKUP_DATETIME, 'IW') AS EARNING_MONTH, 
	NVL(vd.VENDOR_DESCRIPTION, td.VENDORID) AS VENDOR,
	NVL(td.FARE_AMOUNT, 0) AS FARE_AMOUNT,
	NVL(td.TIP_AMOUNT, 0) AS TIP_AMOUNT,
	SUM(td.TOTAL_AMOUNT) AS TOTAL_AMOUNT,
	COUNT(1) AS TRIP_COUNT
FROM YT_TRIP_DATA td
LEFT OUTER JOIN YT_DD_VENDOR vd
ON td.VENDORID = vd.VENDOR_ID
WHERE TRUNC(td.TPEP_PICKUP_DATETIME) = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -4)
AND td.PAYMENT_TYPE <> 3 -- This condition is to filter out the "No charge" trips
GROUP BY TRUNC(td.TPEP_PICKUP_DATETIME, 'IW'), NVL(vd.VENDOR_DESCRIPTION, td.VENDORID), NVL(td.FARE_AMOUNT, 0), NVL(td.TIP_AMOUNT, 0)
ORDER BY 5 DESC, 3 DESC, 4 DESC
;