WITH AGG_TRIP_WEEKLY AS
(
SELECT 
	TRUNC(TPEP_PICKUP_DATETIME, 'IW') AS START_DATE_OF_WEEK, 
	TO_CHAR(TPEP_PICKUP_DATETIME, 'WW') AS WEEK_OF_YEAR, 
	HOUR_OF_DAY, 
	COUNT(1) AS TRIP_COUNT
FROM YT_TRIP_DATA
WHERE TRUNC(TPEP_PICKUP_DATETIME, 'MM') >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -4)
GROUP BY TRUNC(TPEP_PICKUP_DATETIME, 'IW'), TO_CHAR(TPEP_PICKUP_DATETIME, 'WW'), HOUR_OF_DAY
),
BUSIEST_HOURS AS
(
SELECT ATW.*, 
	RANK() OVER(PARTITION BY START_DATE_OF_WEEK ORDER BY TRIP_COUNT DESC) AS BUSIEST_RANK 
FROM AGG_TRIP_WEEKLY ATW
)
SELECT START_DATE_OF_WEEK, WEEK_OF_YEAR, HOUR_OF_DAY, TRIP_COUNT FROM BUSIEST_HOURS WHERE BUSIEST_RANK <= 5;