CREATE TABLE YT_DD_VENDOR 
(
	VENDOR_ID				NUMBER(5) NOT NULL,
	VENDOR_DESCRIPTION		VARCHAR2(100),
	CREATED_TIMESTAMP		TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MODIFIED_TIMESTAMP		TIMESTAMP,
CONSTRAINT PK_VENDORID PRIMARY KEY(VENDOR_ID)
);

CREATE OR REPLACE TRIGGER TRG_VENDOR
  BEFORE INSERT OR UPDATE ON YT_DD_VENDOR
  FOR EACH ROW
BEGIN
  :new.MODIFIED_TIMESTAMP := sysdate;
END;
