CREATE TABLE YT_DD_RATECODEID 
(
	RATECODE_ID				NUMBER(5) NOT NULL,
	RATECODE_DESCRIPTION	VARCHAR2(100),
	CREATED_TIMESTAMP		TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MODIFIED_TIMESTAMP		TIMESTAMP,
CONSTRAINT PK_RATECODEID PRIMARY KEY(RATECODE_ID)
);

CREATE OR REPLACE TRIGGER TRG_RATECODES
  BEFORE INSERT OR UPDATE ON YT_DD_RATECODEID
  FOR EACH ROW
BEGIN
  :new.MODIFIED_TIMESTAMP := sysdate;
END;
