CREATE TABLE YT_DD_PAYTYPE 
(
	PAYTYPE_ID				NUMBER(5) NOT NULL,
	PAYTYPE_DESCRIPTION		VARCHAR2(100),
	CREATED_TIMESTAMP		TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MODIFIED_TIMESTAMP		TIMESTAMP,
CONSTRAINT PK_PAYTYPEID PRIMARY KEY(PAYTYPE_ID)
);

CREATE OR REPLACE TRIGGER TRG_PAYTYPE
  BEFORE INSERT OR UPDATE ON YT_DD_PAYTYPE
  FOR EACH ROW
BEGIN
  :new.MODIFIED_TIMESTAMP := sysdate;
END;
