CREATE TABLE YT_DD_LOCANDZONES 
(
	LOCATION_ID				NUMBER(5) NOT NULL,
	BOROUGH					VARCHAR2(100),
	ZONEE					VARCHAR2(100),
	SERVICE_ZONE			VARCHAR2(100),
	CREATED_TIMESTAMP		TIMESTAMP DEFAULT SYSDATE NOT NULL,
	MODIFIED_TIMESTAMP		TIMESTAMP,
CONSTRAINT PK_LOCATIONID PRIMARY KEY(LOCATION_ID)
);

CREATE OR REPLACE TRIGGER TRG_LOCANDZONES
  BEFORE INSERT OR UPDATE ON YT_DD_LOCANDZONES
  FOR EACH ROW
BEGIN
  :new.MODIFIED_TIMESTAMP := sysdate;
END;
