CREATE TABLE YT_TRIP_DATA
(
	VENDORID 					NUMBER(5) NOT NULL,
	TPEP_PICKUP_DATETIME 		DATE NOT NULL,
	TPEP_DROPOFF_DATETIME		DATE,
	PASSENGER_COUNT				NUMBER(3,0),
	TRIP_DISTANCE				NUMBER(10),
	RATECODEID					NUMBER(5),
	STORE_AND_FWD_FLAG			VARCHAR2(3),
	PULOCATIONID				NUMBER(5),
	DOLOCATIONID				NUMBER(5),
	PAYMENT_TYPE				NUMBER(5),
	FARE_AMOUNT					NUMBER(10,6),
	EXTRA						NUMBER(10,6),
	MTA_TAX						NUMBER(10,6),
	TIP_AMOUNT					NUMBER(10,6),
	TOLLS_AMOUNT				NUMBER(10,6),
	IMPROVEMENT_SURCHARGE		NUMBER(10,6),
	TOTAL_AMOUNT				NUMBER(10,6),
	CONGESTION_SURCHARGE		NUMBER(10,6),
	AIRPORT_FEE					NUMBER(10,6),
	DAY_OF_WEEK					NUMBER(2),
	HOUR_OF_DAY					NUMBER(2)
) 
PARTITION BY RANGE (TPEP_PICKUP_DATETIME)
INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
(partition default_part values less than (to_date('01-JAN-2023','DD-MON-YYYY')));